name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: hazembabiker-2004
          output: "./stats/github-stats.svg"
          hide_border: true
          theme: radical
          bg_color: 0D1117
          title_color: 58A6FF
          icon_color: 58A6FF
          count_private: true
      - name: Generate GitHub Streak Stats
        uses: anuraghazra/github-readme-streak-stats@master
        with:
          user: hazembabiker-2004
          output: "./stats/github-streak-stats.svg"
          theme: radical
          hide_border: true
          background: 0D1117
          ring: 58A6FF
          fire: 58A6FF
          currStreakNum: ffffff
      - name: Generate Top Languages Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: hazembabiker-2004
          output: "./stats/top-langs.svg"
          layout: compact
          theme: radical
          hide_border: true
          bg_color: 0D1117
          title_color: 58A6FF
      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update GitHub Stats" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
